name: Deploy static web app to storage account

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Set up Azure Storage with Terraform
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_resource_group_name: ${{ secrets.TF_VAR_resource_group_name }} 
      TF_VAR_resource_group_location: ${{ secrets.TF_VAR_resource_group_location }} 
      TF_VAR_storage_account_name: ${{ secrets.TF_VAR_storage_account_name }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Apply Terraform
        id: apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: List build directory contents
        run: ls -la ./build

      - name: Upload files to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az storage blob upload-batch --account-name $TF_VAR_storage_account_name -s ./build -d '$web'