name: Terraform Deploy to Azure Storage

on:
  push:
    branches:
      - main
env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:

  terraform:
    name: Set up Azure Storage with Terraform
    runs-on: ubuntu-latest
    outputs:
        STORAGE_ACCOUNT_NAME: ${{ steps.set-storage-account.outputs.STORAGE_ACCOUNT_NAME }}
        STATIC_WEBSITE_URL: ${{ steps.set-static-website.outputs.STATIC_WEBSITE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Apply Terraform
        id: apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Capture storage account
        id: set-storage-account
        working-directory: infra
        run: |
          storage_account_name=$(terraform output -raw storage_account_name | tr -d '\n\r')
          echo "STORAGE_ACCOUNT_NAME=$storage_account_name" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Capture static website URL
        id: set-static-website
        working-directory: infra
        run: |
          static_website_url=$(terraform output -raw static_website_url | tr -d '\n\r')
          echo "STATIC_WEBSITE_URL=$static_website_url" >> "$GITHUB_OUTPUT"
        shell: bash

  deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    needs: [terraform]

    
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Echo environment variables
        run: |
          echo "STORAGE_ACCOUNT_NAME is: ${{ needs.terraform.outputs.STORAGE_ACCOUNT_NAME }}"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: List build directory contents
        run: ls -la ./build

      - name: Upload files to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az storage blob upload-batch --account-name "${{ needs.terraform.outputs.STORAGE_ACCOUNT_NAME }}" -s ./build -d '$web'

      - name: Show Static Website URL
        run: echo "Your site is live at ${{ needs.terraform.outputs.STATIC_WEBSITE_URL }}"
