name: Terraform Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Set up Azure Storage with Terraform
    runs-on: ubuntu-latest

    outputs:
      storage_account_name: ${{ steps.set-storage-account.outputs.storage_account_name }}
      static_website_url: ${{ steps.set-static-website.outputs.static_website_url }}

    steps:
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout code
        uses: actions/checkout@v3
    

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Apply Terraform
        id: apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Capture storage account
        id: set-storage-account
        working-directory: infra
        run: |
          storage_account_name=$(terraform output -raw storage_account_name 2>/dev/null | tr -d '\r\n')
          echo "storage_account_name=$storage_account_name" >> "$GITHUB_OUTPUT"

      - name: Capture static website URL
        id: set-static-website
        working-directory: infra
        run: |
          static_website_url=$(terraform output -raw static_website_url 2>/dev/null | tr -d '\r\n')
          echo "static_website_url=$static_website_url" >> "$GITHUB_OUTPUT"

  deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: List build directory contents
        run: ls -la ./build

      - name: Print Terraform Outputs
        run: |
          echo "Storage Account Name: ${{ needs.terraform.outputs.storage_account_name }}"
          echo "Static Website URL: ${{ needs.terraform.outputs.static_website_url }}"

      - name: Upload files to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name "${{ needs.terraform.outputs.storage_account_name }}" -s ./build --auth-mode key -d '$web'

      - name: Show Static Website URL
        run: echo "Your site is live at ${{ needs.terraform.outputs.static_website_url }}"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
