name: Terraform Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Set up Azure Storage with Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
        # Capture the Terraform outputs as environment variables
        env:
          TF_VAR_storage_account_name: ${{ steps.apply.outputs.storage_account_name }}
          TF_VAR_static_website_url: ${{ steps.apply.outputs.static_website_url }}

      - name: Output Storage Account Name
        run: echo "Storage Account Name: ${{ env.TF_VAR_storage_account_name }}"
      
      - name: Output Static Website URL
        run: echo "Static Website URL: ${{ env.TF_VAR_static_website_url }}"

  deploy:
    name: Build and Deploy React App
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload files to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az storage blob upload-batch --account-name "${{ needs.terraform.outputs.storage_account_name }}" -s ./build -d '$web'
